### ISSUE TITLE
Feature Request: Implement getTree for Uint and Bitfield

### ISSUE THREAD

**Issue by rauljordan** [ferranbt/fastssz#62] opened 2021-10-09 21:49 UTC
In order to generate proofs for beacon states, we need uint and bitfield support. Currently, this panics with unimplemented when trying to generate fastssz code on the Prysm BeaconStateAltair struct due to uint and bitfields missing.

**Comment by ferranbt** [comment] 2021-10-10 08:29
Are you using the ```experimental``` flag for the proofs?

**Comment by rauljordan** [comment] 2021-10-16 14:27
Hi @ferranbt some guidance on how we could implement this for bitlist would be super helpful. Thank you

**Comment by ferranbt** [comment] 2021-10-16 20:49
Hi! Sorry for the delay. You can ping me next time over Discord if it is a hurry. I will try to take a look at this over the weekend. 

The first thing to fix is the hashing of the BeaconState itself. As commented in #61, since you had already a custom BeaconState implementation and your fork of fastssz for Altair (I think) did not implemented it either I did not add neither uints and bitfields to the hashing to pass the BeaconState. I will try to figure that our first and then we can move to the proof.

**Comment by ferranbt** [comment] 2021-10-17 12:11
Do you have the sizes of all the BeaconState fields for the Altair minimal config? I cannot find it anywhere. I want to check if all [these](https://github.com/ferranbt/fastssz/blob/master/spectests/structs.go#L128) lengths are correct.

**Comment by rauljordan** [comment] 2021-10-17 17:22
Hi @ferranbt check out https://github.com/prysmaticlabs/prysm/blob/develop/proto/ssz_proto_library.bzl

**Comment by ferranbt** [comment] 2022-06-17 23:52
In #64 I added some important modifications to the proof system. Now, fastssz reuses the same generated code for hashing to compute the proof. All the spec structs pass as intended.

However, there is a slight problem with `BeaconState`. At [this](https://github.com/ferranbt/fastssz/blob/master/tree.go#L192) step, the prober generates an array with the size of the max limit for a list, in the case of `BeaconState.Validators` that max size is huge (1099511627776). An array of that size cannot be created in Go and it panics.

Even if this can be optimized (since much of these items are empty now) I am not sure if it will ever be optimal to keep the `BeaconState` in this tree data structure for the proofs.

**Comment by ferranbt** [comment] 2022-08-19 06:35
Closing the issue since there is already support for uint and bitfield types on `sszgen`. Please open another issue if you feel necessary to track `BeaconState` proofs.

**Closed by ferranbt** 2022-08-19 06:35 UTC
